
export let sht_filters_2434 = [
  {
    "flt_id": 5618,
    "name": "Временные корзины",
    "filter_node_list": [
      {
        "id": "53594",
        "id_hi": null,
        "name": "366 и более",
        "groupfl": "0",
        "npp": 8,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "366 и более",
        "checked": false
      },
      {
        "id": "53595",
        "id_hi": null,
        "name": "Входящий остаток",
        "groupfl": "0",
        "npp": 1,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "Входящий остаток",
        "checked": false
      },
      {
        "id": "53596",
        "id_hi": null,
        "name": "До востребования",
        "groupfl": "0",
        "npp": 2,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "До востребования",
        "checked": false
      },
      {
        "id": "53597",
        "id_hi": null,
        "name": "ИТОГО",
        "groupfl": "0",
        "npp": 9,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "ИТОГО",
        "checked": false
      },
      {
        "id": "53598",
        "id_hi": null,
        "name": "От 1 до 7 дней",
        "groupfl": "0",
        "npp": 3,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "От 1 до 7 дней",
        "checked": false
      },
      {
        "id": "53599",
        "id_hi": null,
        "name": "От 181 до 365 дней",
        "groupfl": "0",
        "npp": 7,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "От 181 до 365 дней",
        "checked": false
      },
      {
        "id": "53600",
        "id_hi": null,
        "name": "От 31 до 90 дней",
        "groupfl": "0",
        "npp": 5,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "От 31 до 90 дней",
        "checked": false
      },
      {
        "id": "53601",
        "id_hi": null,
        "name": "От 8 до 30 дней",
        "groupfl": "0",
        "npp": 4,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "От 8 до 30 дней",
        "checked": false
      },
      {
        "id": "53602",
        "id_hi": null,
        "name": "От 91 до 180 дней",
        "groupfl": "0",
        "npp": 6,
        "nlevel": 0,
        "flt_id": 5618,
        "label": "От 91 до 180 дней",
        "checked": false
      }
    ]
  },
  {
    "flt_id": 5619,
    "name": "ЦФО и инвестиции",
    "filter_node_list": [
      {
        "id": "39595",
        "id_hi": null,
        "name": "ГО",
        "groupfl": "0",
        "npp": 0,
        "nlevel": 1,
        "flt_id": 5619,
        "label": "ГО",
        "checked": true
      }
    ]
  },
  {
    "flt_id": 5620,
    "name": "Показатели листа",
    "filter_node_list": [
      {
        "id": "141114",
        "id_hi": null,
        "name": "5. Мгновенная ликвидность",
        "groupfl": "0",
        "npp": 6,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "5. Мгновенная ликвидность",
        "checked": false
      },
      {
        "id": "141833",
        "id_hi": null,
        "name": "6. Текущая ликвидность",
        "groupfl": "0",
        "npp": 7,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "6. Текущая ликвидность",
        "checked": false
      },
      {
        "id": "141834",
        "id_hi": null,
        "name": "7. Долгосрочная ликвидность",
        "groupfl": "0",
        "npp": 8,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "7. Долгосрочная ликвидность",
        "checked": false
      },
      {
        "id": "104368",
        "id_hi": null,
        "name": "1. Активы",
        "groupfl": "1",
        "npp": 1,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "1. Активы",
        "children": [
          {
            "id": "104369",
            "id_hi": "104368",
            "name": "1.1. Кредиты",
            "groupfl": "1",
            "npp": 1,
            "nlevel": 1,
            "flt_id": 5620,
            "label": "1.1. Кредиты",
            "children": [
              {
                "id": "104370",
                "id_hi": "104369",
                "name": "1.1.1. Основной долг",
                "groupfl": "0",
                "npp": 1,
                "nlevel": 2,
                "flt_id": 5620,
                "label": "1.1.1. Основной долг",
                "checked": false
              },
              {
                "id": "104371",
                "id_hi": "104369",
                "name": "1.1.2. Проценты",
                "groupfl": "0",
                "npp": 2,
                "nlevel": 2,
                "flt_id": 5620,
                "label": "1.1.2. Проценты",
                "checked": false
              }
            ],
            "checked": false
          }
        ],
        "checked": false
      },
      {
        "id": "104373",
        "id_hi": null,
        "name": "3. GAP (месяц)",
        "groupfl": "0",
        "npp": 3,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "3. GAP (месяц)",
        "checked": false
      },
      {
        "id": "104374",
        "id_hi": null,
        "name": "2. Пассивы",
        "groupfl": "1",
        "npp": 2,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "2. Пассивы",
        "children": [
          {
            "id": "104375",
            "id_hi": "104374",
            "name": "2.1. Депозиты",
            "groupfl": "1",
            "npp": 1,
            "nlevel": 1,
            "flt_id": 5620,
            "label": "2.1. Депозиты",
            "children": [
              {
                "id": "104376",
                "id_hi": "104375",
                "name": "2.1.1. Основной долг",
                "groupfl": "0",
                "npp": 1,
                "nlevel": 2,
                "flt_id": 5620,
                "label": "2.1.1. Основной долг",
                "checked": false
              },
              {
                "id": "104377",
                "id_hi": "104375",
                "name": "2.1.2. Проценты",
                "groupfl": "0",
                "npp": 2,
                "nlevel": 2,
                "flt_id": 5620,
                "label": "2.1.2. Проценты",
                "checked": false
              }
            ],
            "checked": false
          }
        ],
        "checked": false
      },
      {
        "id": "104378",
        "id_hi": null,
        "name": "4. GAP (нарастающим итогом)",
        "groupfl": "0",
        "npp": 5,
        "nlevel": 0,
        "flt_id": 5620,
        "label": "4. GAP (нарастающим итогом)",
        "checked": false
      }
    ]
  }
];

export let sht_info_2434 = [
  {
    "id": 2434,
    "ver_id": 465,
    "longname": "Ликвидность",
    "type_id": 41,
    "proc_id": 195042,
    "color_restrict": 13816570,
    "color_hand_input": 16777139,
    "color_totals": 8454016,
    "color_cons": 16776960,
    "color_confirm": 16711680,
    "color_flt": 8454143,
    "shd_id": null,
    "sch_id": null,
    "grp_id": 1073,
    "link_dscr": null,
    "dreg_plan": null,
    "usr_grp_id": null,
    "link_npp": 1,
    "ent_code": null,
    "sql_rule": null,
    "date_attr": null,
    "src_type": null,
    "split_hie_fl": "0",
    "ime_frmt": null,
    "bop_id": null,
    "disable_parallel": null,
    "exp_proc": null,
    "turn_name_income": "Входящий остаток",
    "turn_name_move": "Оборот",
    "turn_name_outcome": "Исходящий остаток",
    "src_dmsht_id": null,
    "npp": 1,
    "loadtmplfl": "0",
    "code_htom": "LIKVIDNOST",
    "need_recalcfl": "1",
    "color_part_confirm": 4227072,
    "need_recalc_pf_fl": null,
    "confrunfl": "1",
    "sheet_path": "MIS => 2.Бюджет Планирование, контроль, факт => 2017 => 1.0 => GAP отчеты => Ликвидность",
    "color_restrict_hex": "#fad2d2",
    "color_hand_hex": "#b3ffff",
    "color_total_hex": "#80ff80",
    "color_filter_hex": "#ffff80",
    "color_cons_hex": "#00ffff",
    "color_conf_hex": "#0000ff",
    "color_conf_part_hex": "#008040"
  }
];


export let sht_state_2434 = [
  {
    "sht_id": 2434,
    "id_us": 1,
    "filternodes": {
      "5618": [],
      "5619": [
        {
          "id": "39595"
        }
      ],
      "5620": []
    },
    "columnstates": [
      {
        "colId": "ag-Grid-AutoColumn",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": "left",
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53598",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53595",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53596",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53601",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53600",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53602",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53599",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53594",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      },
      {
        "colId": "FLT_ID_5618=>53597",
        "hide": false,
        "aggFunc": null,
        "width": 240,
        "pivotIndex": null,
        "pinned": null,
        "rowGroupIndex": null
      }
    ],
    "expandedgroupids": []
  }
];

export let sht_columns_2434 = [
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53595",
    "name": "Входящий остаток",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53595",
    "order_by": null,
    "npp": 1
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53596",
    "name": "До востребования",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53596",
    "order_by": null,
    "npp": 2
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53598",
    "name": "От 1 до 7 дней",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53598",
    "order_by": null,
    "npp": 3
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53601",
    "name": "От 8 до 30 дней",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53601",
    "order_by": null,
    "npp": 4
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53600",
    "name": "От 31 до 90 дней",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53600",
    "order_by": null,
    "npp": 5
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53602",
    "name": "От 91 до 180 дней",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53602",
    "order_by": null,
    "npp": 6
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53599",
    "name": "От 181 до 365 дней",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53599",
    "order_by": null,
    "npp": 7
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53594",
    "name": "366 и более",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53594",
    "order_by": null,
    "npp": 8
  },
  {
    "anl_type_id": null,
    "anl_id": null,
    "id": "53597",
    "name": "ИТОГО",
    "dfrom": null,
    "period_step": null,
    "editfl": "1",
    "flt_id": 5618,
    "flt_id_node": null,
    "key": "FLT_ID_5618=>53597",
    "order_by": null,
    "npp": 9
  }
];

export let sht_nodes_2434 = [
  {
    "node_key": "FLT_ID_5620=>104368",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "104368",
    "ind_id": "104368",
    "name": "1. Активы",
    "npp": 1,
    "groupfl": "1",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "5864755.22",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "300000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "677.27",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "395298.7",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "986064.88",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "1545643.07",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "1381957.24",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "1555114.06",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 1. Активы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104368,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "5864755.22",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "5864755.22",
    "FLT_ID_5618=>53596": "300000",
    "FLT_ID_5618=>53598": "677.27",
    "FLT_ID_5618=>53601": "395298.7",
    "FLT_ID_5618=>53600": "986064.88",
    "FLT_ID_5618=>53602": "1545643.07",
    "FLT_ID_5618=>53599": "1381957.24",
    "FLT_ID_5618=>53594": "1555114.06",
    "FLT_ID_5618=>53597": "5864755.22"
  },
  {
    "node_key": "FLT_ID_5620=>104374",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "104374",
    "ind_id": "104374",
    "name": "2. Пассивы",
    "npp": 2,
    "groupfl": "1",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "-1000000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "-500000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "-500000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "-500000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "-3000000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 2. Пассивы",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104374,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "-1000000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "-1000000",
    "FLT_ID_5618=>53596": "-500000",
    "FLT_ID_5618=>53598": "0",
    "FLT_ID_5618=>53601": "-500000",
    "FLT_ID_5618=>53600": "0",
    "FLT_ID_5618=>53602": "0",
    "FLT_ID_5618=>53599": "-500000",
    "FLT_ID_5618=>53594": "-3000000",
    "FLT_ID_5618=>53597": "-1000000"
  },
  {
    "node_key": "FLT_ID_5620=>104373",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "104373",
    "ind_id": "104373",
    "name": "3. GAP (месяц)",
    "npp": 3,
    "groupfl": "0",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "4864755.22",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "-200000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "677.27",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "-104701.3",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "986064.88",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "1545643.07",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "881957.24",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "-1444885.94",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 3. GAP (месяц)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104373,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "4864755.22",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "4864755.22",
    "FLT_ID_5618=>53596": "-200000",
    "FLT_ID_5618=>53598": "677.27",
    "FLT_ID_5618=>53601": "-104701.3",
    "FLT_ID_5618=>53600": "986064.88",
    "FLT_ID_5618=>53602": "1545643.07",
    "FLT_ID_5618=>53599": "881957.24",
    "FLT_ID_5618=>53594": "-1444885.94",
    "FLT_ID_5618=>53597": "4864755.22"
  },
  {
    "node_key": "FLT_ID_5620=>104378",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "104378",
    "ind_id": "104378",
    "name": "4. GAP (нарастающим итогом)",
    "npp": 4,
    "groupfl": "0",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "4864755.22",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": "BRUSH.COLOR=255",
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "-200000",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": 86617,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#ff0000",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": "BRUSH.COLOR=255",
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "-199322.73",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": 86617,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#ff0000",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": "BRUSH.COLOR=255",
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "-304024.03",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": 86617,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#ff0000",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "682040.85",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "2227683.92",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "3109641.16",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "1664755.22",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 4. GAP (нарастающим итогом)",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 104378,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "4864755.22",
    "FLT_ID_5618=>53596": "-200000",
    "FLT_ID_5618=>53598": "-199322.73",
    "FLT_ID_5618=>53601": "-304024.03",
    "FLT_ID_5618=>53600": "682040.85",
    "FLT_ID_5618=>53602": "2227683.92",
    "FLT_ID_5618=>53599": "3109641.16",
    "FLT_ID_5618=>53594": "1664755.22",
    "FLT_ID_5618=>53597": "0"
  },
  {
    "node_key": "FLT_ID_5620=>141114",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "141114",
    "ind_id": "141114",
    "name": "5. Мгновенная ликвидность",
    "npp": 5,
    "groupfl": "0",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": "FONT.BOLD=1,BORDER.COLOR=255,BRUSH.COLOR=65535",
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": "комментарий",
        "comment_usr_name": "Создатель базы данных",
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "60",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 1,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": 86609,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#ffff00",
        "font.color": "black",
        "border.color": "#ff0000",
        "font.italic": "0",
        "font.bold": "1"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 5. Мгновенная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141114,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "0",
    "FLT_ID_5618=>53596": "60",
    "FLT_ID_5618=>53598": "0",
    "FLT_ID_5618=>53601": "0",
    "FLT_ID_5618=>53600": "0",
    "FLT_ID_5618=>53602": "0",
    "FLT_ID_5618=>53599": "0",
    "FLT_ID_5618=>53594": "0",
    "FLT_ID_5618=>53597": "0"
  },
  {
    "node_key": "FLT_ID_5620=>141833",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "141833",
    "ind_id": "141833",
    "name": "6. Текущая ликвидность",
    "npp": 6,
    "groupfl": "0",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": "FONT.ITALIC=1,BORDER.COLOR=4227327,BRUSH.COLOR=65280",
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "79.05974",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": 86611,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#00ff00",
        "font.color": "black",
        "border.color": "#ff8040",
        "font.italic": "1",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 6. Текущая ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141833,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "0",
    "FLT_ID_5618=>53596": "0",
    "FLT_ID_5618=>53598": "0",
    "FLT_ID_5618=>53601": "79.05974",
    "FLT_ID_5618=>53600": "0",
    "FLT_ID_5618=>53602": "0",
    "FLT_ID_5618=>53599": "0",
    "FLT_ID_5618=>53594": "0",
    "FLT_ID_5618=>53597": "0"
  },
  {
    "node_key": "FLT_ID_5620=>141834",
    "skey": null,
    "flt_id": "5620",
    "flt_item_id": "141834",
    "ind_id": "141834",
    "name": "7. Долгосрочная ликвидность",
    "npp": 7,
    "groupfl": "0",
    "dtype_id": null,
    "color": null,
    "consfl": null,
    "confirmfl": "0",
    "has_data": 1,
    "prim": null,
    "atr_type": null,
    "round_size": null,
    "ent_id": null,
    "column_data": [
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53595",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53596",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53598",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53601",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53600",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53602",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53599",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      },
      {
        "styles": "FONT.BOLD=1,BORDER.COLOR=255,BRUSH.COLOR=65535",
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53594",
        "sql_value": "51.83713533333333333333333333333333333333",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": 86615,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#ffff00",
        "font.color": "black",
        "border.color": "#ff0000",
        "font.italic": "0",
        "font.bold": "1"
      },
      {
        "styles": null,
        "flt_dscr": "ЦФО и инвестиции = ГО\nПоказатели листа = 7. Долгосрочная ликвидность",
        "comment_text": null,
        "comment_usr_name": null,
        "ind_id": 141834,
        "key": "FLT_ID_5618=>53597",
        "sql_value": "0",
        "editfl": 0,
        "description": null,
        "oldfl": 0,
        "commentfl": 0,
        "confirmfl": "0",
        "groupfl": null,
        "mark_tbl_id": null,
        "formcode": null,
        "reffield": null,
        "refsend": null,
        "refrcv": null,
        "expr": null,
        "brush.color": "#fad2d2",
        "font.color": "black",
        "border.color": "black",
        "font.italic": "0",
        "font.bold": "0"
      }
    ],
    "FLT_ID_5618=>53595": "0",
    "FLT_ID_5618=>53596": "0",
    "FLT_ID_5618=>53598": "0",
    "FLT_ID_5618=>53601": "0",
    "FLT_ID_5618=>53600": "0",
    "FLT_ID_5618=>53602": "0",
    "FLT_ID_5618=>53599": "0",
    "FLT_ID_5618=>53594": "51.83713533333333333333333333333333333333",
    "FLT_ID_5618=>53597": "0"
  }
];

