
//just to try redux
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_CLEAR = "DATA_CLEAR";
export const API_ERRORED = "API_ERRORED";
export const ADD_LOADING_GUID = "ADD_LOADING_GUID";
export const SHEET_FILTER_LIST_REQUESTED = "SHEET_FILTER_LIST_REQUESTED";
export const SHEET_FILTER_LIST_LOADED = "SHEET_FILTER_LIST_LOADED";
export const SHEET_STATE_REQUESTED = "SHEET_STATE_REQUESTED";
export const SHEET_STATE_LOADED = "SHEET_STATE_LOADED";

